# Generated by Django 5.2 on 2025-04-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userprofile_clipped_coupons'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='image',
            field=models.CharField(default='coupon1.png', max_length=255),
        ),
    ]
